franka_pole_external_position_controller:
  type: franka_pole/ExternalPositionController

franka_pole_simple_position_controller:
  type: franka_pole/SimplePositionController

franka_pole_test_position_controller:
  type: franka_pole/TestPositionController

franka_pole_external_acceleration_controller:
  type: franka_pole/ExternalAccelerationController

franka_pole_simple_acceleration_controller:
  type: franka_pole/SimpleAccelerationController

franka_pole_test_acceleration_controller:
  type: franka_pole/TestAccelerationController