$(arg namespace)_external_position_controller:
  namespace: $(arg namespace)
  type: franka_pole/ExternalPositionController

$(arg namespace)_simple_position_controller:
  namespace: $(arg namespace)
  type: franka_pole/SimplePositionController

$(arg namespace)_test_position_controller:
  namespace: $(arg namespace)
  type: franka_pole/TestPositionController

$(arg namespace)_external_acceleration_controller:
  namespace: $(arg namespace)
  type: franka_pole/ExternalAccelerationController

$(arg namespace)_simple_acceleration_controller:
  namespace: $(arg namespace)
  type: franka_pole/SimpleAccelerationController

$(arg namespace)_test_acceleration_controller:
  namespace: $(arg namespace)
  type: franka_pole/TestAccelerationController