$(arg namespace)_external_position_controller:
  namespace: $(arg namespace)
  type: franka_pendulum/ExternalPositionController

$(arg namespace)_simple_position_controller:
  namespace: $(arg namespace)
  type: franka_pendulum/SimplePositionController

$(arg namespace)_test_position_controller:
  namespace: $(arg namespace)
  type: franka_pendulum/TestPositionController

$(arg namespace)_external_acceleration_controller:
  namespace: $(arg namespace)
  type: franka_pendulum/ExternalAccelerationController

$(arg namespace)_simple_acceleration_controller:
  namespace: $(arg namespace)
  type: franka_pendulum/SimpleAccelerationController

$(arg namespace)_test_acceleration_controller:
  namespace: $(arg namespace)
  type: franka_pendulum/TestAccelerationController