<?xml version='1.0' encoding='utf-8'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="franka_pole">
  <xacro:arg name="arm_id" default="panda" />
  
  <!-- Create a simulatable URDF -->
  <xacro:include filename="$(find franka_description)/robots/utils.xacro" />
  <xacro:include filename="$(find franka_description)/robots/panda_gazebo.xacro" />
  <xacro:panda_arm arm_id="$(arg arm_id)" />
  <xacro:hand arm_id="$(arg arm_id)" rpy="0 0 ${-pi/4}" connected_to="$(arg arm_id)_link8" />
  <xacro:gazebo-joint joint="$(arg arm_id)_finger_joint1" transmission="hardware_interface/EffortJointInterface" />
  <xacro:gazebo-joint joint="$(arg arm_id)_finger_joint2" transmission="hardware_interface/EffortJointInterface" />
  
  <!-- Gazebo requires a joint to a link called "world" for statically mounted robots -->
  <link name="world" />
    <joint name="world_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="world" />
    <child  link="$(arg arm_id)_link0" />
  </joint>
  <xacro:gazebo-joint joint="$(arg arm_id)_joint1" transmission="hardware_interface/EffortJointInterface" />
  <xacro:gazebo-joint joint="$(arg arm_id)_joint2" transmission="hardware_interface/EffortJointInterface" />
  <xacro:gazebo-joint joint="$(arg arm_id)_joint3" transmission="hardware_interface/EffortJointInterface" />
  <xacro:gazebo-joint joint="$(arg arm_id)_joint4" transmission="hardware_interface/EffortJointInterface" />
  <xacro:gazebo-joint joint="$(arg arm_id)_joint5" transmission="hardware_interface/EffortJointInterface" />
  <xacro:gazebo-joint joint="$(arg arm_id)_joint6" transmission="hardware_interface/EffortJointInterface" />
  <xacro:gazebo-joint joint="$(arg arm_id)_joint7" transmission="hardware_interface/EffortJointInterface" />
  <xacro:transmission-franka-state arm_id="$(arg arm_id)" />
  <xacro:transmission-franka-model arm_id="$(arg arm_id)" root="$(arg arm_id)_joint1" tip="$(arg arm_id)_joint8" />

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <controlPeriod>0.001</controlPeriod>
      <robotSimType>franka_gazebo/FrankaHWSim</robotSimType>
    </plugin>
    <plugin name="franka_pole_plugin" filename="libfranka_pole_plugin.so">
    </plugin>
    <self_collide>true</self_collide>
  </gazebo>


  <!-- Pendulum -->  
  <xacro:property name="lower_mass" value="0.5" />
  <xacro:property name="upper_mass" value="0.1" />
  <xacro:property name="ball_mass" value="0.1" />
  <xacro:property name="beam_mass" value="0.05" />
  <xacro:property name="beam_length" value="0.6" />
  <xacro:property name="beam_radius" value="0.01" />
  <xacro:property name="ball_radius" value="0.05" />

  <!-- Connection -->   
  <joint name="$(arg arm_id)_pole_joint_connection" type="fixed">
    <origin xyz="0.071 -0.071 0.0" rpy="${pi} 0 ${-pi/4}" />
    <parent link="$(arg arm_id)_link8" />
    <child  link="$(arg arm_id)_pole_link_lower" />
  </joint>
  
  <!-- Lower bearing -->
  <link name="$(arg arm_id)_pole_link_lower">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://franka_pole/meshes/visual/2D_lower.dae"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${lower_mass}"/>
      <inertia
      ixx="0.0" ixy="0.0" ixz="0.0"
      iyy="0.0" iyz="0.0"
      izz="0.0"/>
    </inertial>
  </link>
  
  <joint name="$(arg arm_id)_pole_joint_y" type="revolute">
    <parent link="$(arg arm_id)_pole_link_lower"/>
    <child link="$(arg arm_id)_pole_link_middle"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit velocity="1000000" lower="${-20*pi/180}" effort="0" upper="${20*pi/180}" />
    <dynamics damping="0.0"/>
  </joint>

  <!-- Middle bearing -->
  <link name="$(arg arm_id)_pole_link_middle">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://franka_pole/meshes/visual/2D_middle.dae"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
      ixx="0.0" ixy="0.0" ixz="0.0"
      iyy="0.0" iyz="0.0"
      izz="0.0"/>
    </inertial>
  </link>
  
  <joint name="$(arg arm_id)_pole_joint_x" type="revolute">
    <parent link="$(arg arm_id)_pole_link_middle"/>
    <child link="$(arg arm_id)_pole_link_upper"/>
    <origin xyz="0 0 0.012" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit velocity="1000000" lower="${-20*pi/180}" effort="0" upper="${20*pi/180}" />
    <dynamics damping="0.0"/>
  </joint>
  
  <!-- Upper bearing and beam -->
  <link name="$(arg arm_id)_pole_link_upper">
    <visual>
      <origin xyz="0 0 ${beam_length/2.0 + 0.03}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${beam_length - 0.06}" radius = "${beam_radius}"/>
      </geometry>
    </visual>
    <visual>
      <origin xyz="0 0 -0.012" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://franka_pole/meshes/visual/2D_upper.dae"/>
      </geometry>
    </visual>
    
    <inertial>
      <origin xyz="0 0 ${beam_length/2.0}" rpy="0 0 0"/>
      <mass value="${beam_mass}"/>
      <inertia
      ixx="${beam_mass * beam_length*beam_length / 12.0 + beam_mass * beam_radius*beam_radius / 4.0}" ixy="0.0" ixz="0.0"
      iyy="${beam_mass * beam_length*beam_length / 12.0 + beam_mass * beam_radius*beam_radius / 4.0}" iyz="0.0"
      izz="${beam_mass * beam_radius*beam_radius / 2.0}"/>
    </inertial>
  </link>
  
  <joint name="$(arg arm_id)_pole_joint_ball" type="fixed">
    <parent link="$(arg arm_id)_pole_link_upper"/>
    <child link="$(arg arm_id)_pole_link_ball"/>
    <origin xyz="0 0 ${beam_length}" rpy="0 0 0"/>
  </joint>

  <!-- Ball -->
  <link name="$(arg arm_id)_pole_link_ball">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius = "${ball_radius}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${ball_mass}"/>
      <inertia
      ixx="${2.0 * ball_mass * ball_radius*ball_radius / 5.0}" ixy="0.0" ixz="0.0"
      iyy="${2.0 * ball_mass * ball_radius*ball_radius / 5.0}" iyz="0.0"
      izz="${2.0 * ball_mass * ball_radius*ball_radius / 5.0}"/>
    </inertial>
  </link>
  
  <transmission name="$(arg arm_id)_pole_joint_y_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="$(arg arm_id)_pole_joint_y">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="$(arg arm_id)_pole_joint_y_motor">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </actuator>
  </transmission>
  <transmission name="$(arg arm_id)_pole_joint_x_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="$(arg arm_id)_pole_joint_x">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="$(arg arm_id)_pole_joint_x_motor">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </actuator>
  </transmission>
</robot>
